import type {
  Match,
  MatchPlayer,
  MatchResult,
  MatchStatus,
  Position,
} from "@prisma/client";

/**
 * Pure helpers shared by the Matches server actions and client calendar UI
 * (no `server-only`, no Prisma client import — safe to bundle on the client).
 *
 * Dates are handled via explicit y/m/d components (server-local) so the admin
 * calendar never drifts across timezones and round-trips with the public
 * `MatchScheduleTimeline` (which reads `date.getDate()` in the same tz).
 */

/** en-dash separator used to store a kickoff time range as "18:00–20:00". */
export const KICKOFF_SEPARATOR = "–";

/** Max rows generated by a single weekly recurrence (safety cap ~1 year). */
export const MAX_OCCURRENCES = 52;

/** A club player as shown in the finish-match lineup picker. */
export type RosterPlayer = Readonly<{
  id: string;
  name: string;
  imageUrl: string | null;
  position: Position | null;
  jerseyNumber: number | null;
}>;

/** One player's stored per-match line in a match's lineup. */
export type MatchLineupDTO = Readonly<{
  playerId: string;
  name: string;
  goals: number;
  assists: number;
  cleanSheets: number;
  yellowCards: number;
  redCards: number;
  motm: number;
  saves: number;
}>;

/** A Prisma MatchPlayer joined with the player's display name. */
type MatchPlayerWithName = MatchPlayer & { player: { name: string } };

/** Match row with its lineup eagerly included (for the admin calendar). */
export type MatchWithLineup = Match & { lineup?: MatchPlayerWithName[] };

/** Plain, serialisable shape of a Match for client components. */
export type MatchDTO = Readonly<{
  id: string;
  opponent: string;
  /** server-local calendar parts, used for grouping + calendar cells */
  y: number;
  m: number;
  d: number;
  dateISO: string;
  matchweek: string | null;
  venue: string | null;
  field: string | null;
  kickoff: string | null;
  startTime: string | null;
  endTime: string | null;
  status: MatchStatus;
  goalsFor: number | null;
  goalsAgainst: number | null;
  result: MatchResult | null;
  notes: string | null;
  seriesId: string | null;
  lineup: readonly MatchLineupDTO[];
}>;

const TIME_PATTERN = /(\d{1,2})[:.](\d{2})/g;

/** Split a stored kickoff string ("18:00–20:00") into start/end "HH:MM". */
export function parseKickoff(kickoff: string | null): {
  start: string | null;
  end: string | null;
} {
  if (!kickoff) {
    return { start: null, end: null };
  }
  const times = [...kickoff.matchAll(TIME_PATTERN)].map(
    (match) => `${match[1].padStart(2, "0")}:${match[2]}`,
  );
  return { start: times[0] ?? null, end: times[1] ?? null };
}

/** Join two "HH:MM" values into the stored "HH:MM–HH:MM" string, or null. */
export function buildKickoff(
  start: string | null | undefined,
  end: string | null | undefined,
): string | null {
  if (!start || !end) {
    return null;
  }
  return `${start}${KICKOFF_SEPARATOR}${end}`;
}

/** Map a Prisma Match (with optional lineup) to the client DTO. */
export function toMatchDTO(match: MatchWithLineup): MatchDTO {
  const { date } = match;
  const { start, end } = parseKickoff(match.kickoff);
  const lineup: MatchLineupDTO[] = (match.lineup ?? []).map((row) => ({
    playerId: row.playerId,
    name: row.player.name,
    goals: row.goals,
    assists: row.assists,
    cleanSheets: row.cleanSheets,
    yellowCards: row.yellowCards,
    redCards: row.redCards,
    motm: row.motm,
    saves: row.saves,
  }));
  return {
    id: match.id,
    opponent: match.opponent,
    y: date.getFullYear(),
    m: date.getMonth(),
    d: date.getDate(),
    dateISO: date.toISOString(),
    matchweek: match.matchweek,
    venue: match.venue,
    field: match.field,
    kickoff: match.kickoff,
    startTime: start,
    endTime: end,
    status: match.status,
    goalsFor: match.goalsFor,
    goalsAgainst: match.goalsAgainst,
    result: match.result,
    notes: match.notes,
    seriesId: match.seriesId,
    lineup,
  };
}

/** Combine a "YYYY-MM-DD" date and optional "HH:MM" into a server-local Date. */
export function combineDateTime(
  dateStr: string,
  timeStr: string | null,
): Date {
  const [year, month, day] = dateStr.split("-").map(Number);
  const [hours, minutes] = (timeStr ?? "00:00").split(":").map(Number);
  return new Date(
    year,
    (month ?? 1) - 1,
    day ?? 1,
    hours ?? 0,
    minutes ?? 0,
    0,
    0,
  );
}

/** Expand a weekly series: `start`, +7d, … up to and including `until`. */
export function expandWeekly(start: Date, until: Date): Date[] {
  const dates: Date[] = [];
  const cursor = new Date(start);
  while (cursor.getTime() <= until.getTime() && dates.length < MAX_OCCURRENCES) {
    dates.push(new Date(cursor));
    cursor.setDate(cursor.getDate() + 7);
  }
  return dates;
}

/** Derive WIN/DRAW/LOSS from a score (from Bester's perspective). */
export function resultFromScore(
  goalsFor: number,
  goalsAgainst: number,
): MatchResult {
  if (goalsFor > goalsAgainst) {
    return "WIN";
  }
  if (goalsAgainst > goalsFor) {
    return "LOSS";
  }
  return "DRAW";
}

/** ISO-8601 week number for a Date. */
export function isoWeek(date: Date): number {
  const utc = new Date(
    Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()),
  );
  const weekday = utc.getUTCDay() || 7;
  utc.setUTCDate(utc.getUTCDate() + 4 - weekday);
  const yearStart = new Date(Date.UTC(utc.getUTCFullYear(), 0, 1));
  const diffDays = (utc.getTime() - yearStart.getTime()) / 86_400_000;
  return Math.ceil((diffDays + 1) / 7);
}

/** Auto-suggest a "Week N" label from a "YYYY-MM-DD" string. */
export function suggestMatchweek(dateStr: string): string {
  if (!dateStr) {
    return "";
  }
  const [year, month, day] = dateStr.split("-").map(Number);
  if (!year || !month || !day) {
    return "";
  }
  return `Week ${isoWeek(new Date(year, month - 1, day))}`;
}

const TRAILING_NUMBER = /(\d+)\s*$/;

/** For recurrence: keep the base label on the first row, +N on later rows. */
export function incrementMatchweek(
  label: string | null | undefined,
  step: number,
): string | null {
  const trimmed = (label ?? "").trim();
  if (!trimmed) {
    return null;
  }
  if (step === 0) {
    return trimmed;
  }
  const match = TRAILING_NUMBER.exec(trimmed);
  if (!match || match.index === undefined) {
    return trimmed;
  }
  const next = Number(match[1]) + step;
  return `${trimmed.slice(0, match.index)}${next}`;
}

/** Stable key for a calendar day ("2026-0-10"). */
export function dateKey(year: number, month: number, day: number): string {
  return `${year}-${month}-${day}`;
}

/** "Sat 10 Jan 2026" style label from DTO parts. */
export function longDateLabel(year: number, month: number, day: number): string {
  return new Intl.DateTimeFormat("en-US", {
    weekday: "short",
    day: "numeric",
    month: "short",
    year: "numeric",
  }).format(new Date(year, month, day));
}

/** "Jan 2026" month-group label. */
export function monthLabel(year: number, month: number): string {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    year: "numeric",
  }).format(new Date(year, month, 1));
}

/** Weekday name ("Saturday") from a "YYYY-MM-DD" string, or "" if invalid. */
export function weekdayName(dateStr: string): string {
  if (!dateStr) {
    return "";
  }
  const [year, month, day] = dateStr.split("-").map(Number);
  if (!year || !month || !day) {
    return "";
  }
  return new Intl.DateTimeFormat("en-US", { weekday: "long" }).format(
    new Date(year, month - 1, day),
  );
}

/** Case-insensitive search over a fixture's text fields. Empty query = all. */
export function matchesQuery(match: MatchDTO, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (q === "") {
    return true;
  }
  const fields = [
    match.opponent,
    match.venue,
    match.field,
    match.matchweek,
    match.notes,
  ];
  return fields.some((field) => (field ?? "").toLowerCase().includes(q));
}

function startOfDayMs(date: Date): number {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime();
}

function endOfDayMs(date: Date): number {
  return new Date(
    date.getFullYear(),
    date.getMonth(),
    date.getDate(),
    23,
    59,
    59,
    999,
  ).getTime();
}

/** Whether a fixture's calendar day is within an inclusive [from, to] range. */
export function withinDateRange(
  match: MatchDTO,
  range: { from?: Date; to?: Date } | undefined,
): boolean {
  if (!range?.from) {
    return true;
  }
  const day = new Date(match.y, match.m, match.d).getTime();
  return day >= startOfDayMs(range.from) && day <= endOfDayMs(range.to ?? range.from);
}

/** Format a Date to the "YYYY-MM-DD" value a native date input expects. */
export function toDateInputValue(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
